Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-pe_build")
    config.pe_build.download_root = "http://s3.amazonaws.com/pe-builds/released/:version"
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end
